### ISSUE TITLE
Promjena konfiguracije sigurnosti za mogućnost pristupa aktivacije s emaila

### ISSUE THREAD

**Issue by jmigac** [dposavec/WS.Security#28]
Promjena konfiguracije sigurnosti za mogućnost pristupa na endpoint /api/v1/users/{id}/{activationCode}

https://github.com/dposavec/WS.Security/blob/main/Software/src/main/java/org/foi/emp/carmanagement/configs/WebSecurityConfig.java

Izvršiti promjene nad metodom void configure() da se može njoj pristupiti bez Bearera

Following link could be useful for configuration.
(https://stackoverflow.com/a/34994299/15520028)

**Comment by dposavec** [comment]
I will take a shoot
