### ISSUE TITLE
Kreiranje User klase

### ISSUE THREAD

**Issue by dposavec** [dposavec/WS.Security#5]

**Comment by jmigac** [comment]
Security wise, try to implement activation code for account. Its the same principal as on other web sites. When you register (your case is through postman), send email to registered user (https://www.baeldung.com/spring-email), tutorial is provided. Also send him the code for activation. Code could be UUID4, (tutorial how to generate UUID v4 is provided) https://www.baeldung.com/java-uuid. And on next login, user can activate his account on sent uuid 4 in email.

**Comment by jmigac** [comment]
Pull request is approved. @dposavec 
When you merge pull request and you think you won't make any updates to ticket #5, close it.

**Comment by jmigac** [comment]
Java security package is already having an implemented rich User class for implementation of user authentification and authorization.
If you gonna User class from security package, **close this issue**.
